# Generated by Django 4.1.4 on 2022-12-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('valid_until', models.DateField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
