# Generated by Django 4.1.4 on 2022-12-10 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_name', models.TextField()),
                ('promo_description', models.TextField()),
                ('promo_start', models.DateTimeField()),
                ('promo_end', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='products',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 10, 52, 8, 948570)),
        ),
    ]
