# Generated by Django 4.1.4 on 2022-12-10 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_clients_promotions_remove_products_valid_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='promo_products',
            field=models.ManyToManyField(to='main.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 11, 0, 40, 132800)),
        ),
    ]
