# Generated by Django 4.1.4 on 2022-12-10 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_promotions_promo_products_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.AlterField(
            model_name='products',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 11, 27, 53, 546529)),
        ),
    ]
