# Generated by Django 4.1.4 on 2022-12-10 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_clients_alter_products_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 12, 48, 34, 728687)),
        ),
    ]
