# Generated by Django 4.1.4 on 2022-12-10 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_products_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 14, 26, 26, 119552)),
        ),
    ]
