# Generated by Django 4.1.4 on 2022-12-10 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_products_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 14, 22, 23, 187378)),
        ),
    ]
