# Generated by Django 4.1.6 on 2023-02-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_promo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
