# Generated by Django 4.1.6 on 2023-02-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_products_product_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_img',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_promo',
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='Brak opisu', max_length=1000),
        ),
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='promo',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.TextField(max_length=50),
        ),
    ]
